### ISSUE TITLE
Prevent fatal error when importing options

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1020]
A fatal error can occur when  a site has Cloudflare enabled, then options are exported and imported into a fresh install (e.g. when doing a manual update). 
```
Fatal error: Uncaught Error: Call to undefined function set_rocket_cloudflare_cache_level() in .../wp-rocket/inc/admin/options.php:88 
Stack trace:
#0 /wp-includes/class-wp-hook.php(288): rocket_after_save_options(Array, Array)
#1 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 //wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /wp-includes/option.php(401): do_action('update_option_w...', Array, Array, 'wp_rocket_setti...')
#4 /plugins/wp-rocket/inc/classes/admin/class-options.php(81): update_option('wp_rocket_setti...', Array)
#5 /wp-rocket/inc/admin/admin.php(554): WP_Rocket\Admin\Options->set('settings', Array)
#6 wp-includes/class-wp-hook.php(286): in /wp-content/plugins/wp-rocket/inc/admin/options.php on line 88
```
(edited paths to remove domain name)

**Comment by alfonso100** [comment]
I have noticed this issue in version 3.3.5.2, tested it in 2 different sites.

Exporting options from a site with cloudflare add-on enabled, and importing on a fresh install leads to this error:

`Fatal error: Call to undefined function set_rocket_cloudflare_cache_level() in /home/xxxx/public_html/rocket/wp-content/plugins/wp-rocket/inc/admin/options.php on line 118
`

**Comment by viobru** [comment]
The issue was confirmed on this ticket too: https://secure.helpscout.net/conversation/982264697/127219?folderId=3051575

**Comment by Tabrisrp** [comment]
This should be fixed with PR #2112
