### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: preg_split()

### ISSUE THREAD

**Issue by madeITBelgium** [wp-media/wp-rocket#4509]
**Describe the bug**
After updating to 3.10.3 I have 500 errors on different websites.

**To Reproduce**
1. Update to 3.10.3

```
2021/11/17 13:59:29 [error] 2590047#2590047: *9798216 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: preg_split(): Argument #2 ($subject) must be of type string, null given in /home/xxx/web/xxx.be/public_html/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php:522
Stack trace:
#0 /home/xxx/web/xxx/public_html/wp-content/plugins/wp-rocket/inc/Dependencies/RocketLazyload/Image.php(522): preg_split()
#1 /home/xxx/web/xxx/public_html/wp-includes/class-wp-hook.php(303): WP_Rocket\Dependencies\RocketLazyload\Image->convertSmilies()
#2 /home/xxx/web/xxx/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#3 /home/xxx/web/xxx/public_html/wp-includes/formatting.php(3823): apply_filters()
#4 /home/xxx/web/xxx/public_html/wp-includes/class-wp-hook.php(303): wp_trim_excerpt()
#5 /home/xxx/web/xxx/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters()
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @madeITBelgium could you reach our support and share WP/SFTP credentials of the affected website, so we can investigate the problem?

**Comment by madeITBelgium** [comment]
@piotrbak Thank you. I sended an e-mail to contact@wp-rocket.me
