### ISSUE TITLE
Fatal Error when activating the plugin (activation not found)

### ISSUE THREAD

**Issue by Preen** [wp-media/wp-rocket#5303]
**Describe the bug**
Have installed the plugin via composer.
When activating the plugin I get this error:

```
Plugin could not be activated because it triggered a fatal error.
Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class "WP_Rocket\Engine\Activation\Activation" not found in /var/www/html/web/wp/wp-includes/class-wp-hook.php:307 Stack trace: #0 /var/www/html/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #1 /var/www/html/web/wp/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #2 /var/www/html/web/wp/wp-admin/plugins.php(194): do_action('activate_wp-roc...') #3 {main} thrown in /var/www/html/web/wp/wp-includes/class-wp-hook.php on line 307


PHP: 8.1.9
WP: 5.9.3

**Comment by piotrbak** [comment]
Hello @Preen thank you for creating the issue. Could you confirm that you followed our documentation when installing the plugin?
https://docs.wp-rocket.me/article/1301-wp-rocket-installation-from-github-using-composer

If so and the problem still exists, please contact our Support Team and we'll see what's going on:
https://wp-rocket.me/support/
