### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: when setting preload rows count filter is set to null

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5573]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
A fatal error is added to the debug.log when setting `rocket_preload_cache_pending_jobs_cron_rows_count` filter to null (no problem on the FE)

**To Reproduce**
1. Enable preload
2. Set the filter mentioned above to Null
3. Change permalinks and save
4. Check debug.log
```
[16-Nov-2022 11:49:29 UTC] PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Preload\Database\Queries\Cache::get_pending_jobs(): Argument #1 ($total) must be of type int, null given, called in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/PreloadUrl.php on line 185 and defined in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Database/Queries/Cache.php:319
Stack trace:
#0 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Controller/PreloadUrl.php(185): WP_Rocket\Engine\Preload\Database\Queries\Cache->get_pending_jobs()
#1 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Cron/Subscriber.php(96): WP_Rocket\Engine\Preload\Controller\PreloadUrl->process_pending_jobs()
#2 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Preload\Cron\Subscriber->process_pending_urls()
#3 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#5 /var/www/new.rocketlabsqa.ovh/htdocs/wp-cron.php(188): do_action_ref_array()
#6 {main}
  thrown in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Preload/Database/Queries/Cache.php on line 319
```

**Expected behavior**
No Fatal error in debug.log

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
