### ISSUE TITLE
Dev branch: fatal error upon preload

### ISSUE THREAD

**Issue by glueckpress** [wp-media/wp-rocket#576]
[branch-2.11](https://github.com/wp-media/wp-rocket/tree/branch-2.11) currently throws a fatal error upon triggering a preload via toolbar link:

```
Notice: Undefined index: rocket_sitemap_background_process in /…/wp-content/plugins/wp-rocket/inc/functions/bots.php on line 134

Fatal error: 
Uncaught Error: Call to a member function push_to_queue() on null in /…/wp-content/plugins/wp-rocket/inc/functions/bots.php:167 
Stack trace: 
#0 /…/wp-content/plugins/wp-rocket/inc/functions/bots.php(106): run_rocket_sitemap_preload() 
#1 /…/wp-content/plugins/wp-rocket/inc/common/purge.php(486): run_rocket_preload_cache('cache-preload') 
#2 /…/wp-includes/class-wp-hook.php(286): do_admin_post_rocket_preload_cache('') 
#3 /…/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) 
#4 /…/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#5 /…/wp-admin/admin-post.php(69): do_action('admin_post_prel...') 
#6 {main} thrown in /…/wp-content/plugins/wp-rocket/inc/functions/bots.php on line 167
```

**Comment by Tabrisrp** [comment]
Fixed in alpha1
