### ISSUE TITLE
Fatal error: Too few arguments to function WP_Rocket\Engine\Media\AboveTheFold\WarmUp\Controller::__construct() when activating WPR 3.16-alpha1 

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6506]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version > 3.16-alpha1 ✓
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WPR 3.16-alpha1 cannot be activated due to a fatal error. 

**To Reproduce**
1. Install WPR 3.16-alpha1 (through zip, branch [feature/lcp-above-the-fold-optimization](https://github.com/wp-media/wp-rocket/tree/feature/lcp-above-the-fold-optimization))
2. Activate the WPR plugin
3. Notice that activation failed due to a fatal error
4. Inspect the debug.log file and notice the error:

`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_Rocket\Engine\Media\AboveTheFold\WarmUp\Controller::__construct(), 2 passed and exactly 4 expected in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/WarmUp/Controller.php:48
Stack trace:
#0 [internal function]: WP_Rocket\Engine\Media\AboveTheFold\WarmUp\Controller->__construct()
#1 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Definition/Definition.php(256): ReflectionClass->newInstanceArgs()
#2 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Definition/Definition.php(212): WP_Rocket\Dependencies\League\Container\Definition\Definition->resolveClass()
#3 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Definition/DefinitionAggregate.php(94): WP_Rocket\Dependencies\League\Container\Definition\Definition->resolve()
#4 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php(157): WP_Rocket\Dependencies\League\Container\Definition\DefinitionAggregate->resolve()
#5 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/Activation/ServiceProvider.php(46): WP_Rocket\Dependencies\League\Container\Container->get()
#6 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/ServiceProvider/ServiceProviderAggregate.php(102): WP_Rocket\Engine\Media\AboveTheFold\Activation\ServiceProvider->register()
#7 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Dependencies/League/Container/Container.php(172): WP_Rocket\Dependencies\League\Container\ServiceProvider\ServiceProviderAggregate->register()
#8 /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Activation/Activation.php(54): WP_Rocket\Dependencies\League\Container\Container->get()
#9 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Activation\Activation::activate_plugin()
#10 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#11 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#12 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/includes/plugin.php(705): do_action()
#13 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/plugins.php(60): activate_plugin()
#14 {main}
  thrown in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Media/AboveTheFold/WarmUp/Controller.php on line 48
[25-Mar-2024 06:13:16 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/js_composer/include/autoload/vc-pages/automapper.php on line 29`

**Expected behavior**
No fatal error when activating WPR.

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by hanna-meda** [comment]
Confirmed as fixed.
