### ISSUE TITLE
Fatal error when Callback doesn't exist (Clearing the cache)

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#6759]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
If there is no callback registered for the hook `deleted_post` in the following line, a fatal error will be thrown: https://github.com/wp-media/wp-rocket/blob/afe019d352c153c1cfefbf73be51c000ff28b87f/inc/ThirdParty/Plugins/CDN/Cloudflare.php#L488

This seems to be happening with the cache is cleared.

The error in question is:

```
Fatal error: Uncaught Error: key_exists(): Argument #2 ($array) must be of type array, null given in /www/montlickwp_290/public/wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/CDN/Cloudflare.php on line 490 Call stack: key_exists() wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/CDN/Cloudflare.php:490 WP_Rocket\T\P\C\Cloudflare::unregister_callback() wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/CDN/Cloudflare.php:469 WP_Rocket\T\P\C\Cloudflare::unregister_cloudflare_clean_on_post() wp-includes/class-wp-hook.php:324 WP_Hook::apply_filters() wp-includes/class-wp-hook.php:348 WP_Hook::do_action() wp-includes/plugin.php:517 do_action() wp-settings.php:695 require_once() wp-config.php:100 require_once() wp-load.php:50 require_once() wp-admin/admin.php:34 require_once() wp-admin/plugins.php:10
```

As discussed in the slack thread, `we can easily cast against it to be always array or we can bailout if no callbacks are registered.`

**Expected behavior**
No fatal error should be thrown

**Additional context**
[Slack thread](https://wp-media.slack.com/archives/C43T1AYMQ/p1720035131782639)
[HelpScout Ticket](https://secure.helpscout.net/conversation/2642792200/500788?folderId=3963184)

**Acceptance Criteria (for WP Media team use only)**
- Guard to prevent having a fatal error

**Comment by jekayode** [comment]
Similar case: https://onecomhelp.zendesk.com/agent/tickets/18038500 but with WordPress 7.1-beta1

**Comment by alfonso100** [comment]
another case here: https://onecomhelp.zendesk.com/agent/tickets/18036949
WP Version 7.1-beta3
[Slack thread](https://group-onecom.slack.com/archives/C08EFUGUH5G/p1784834042523869)

**Comment by OzzykiGit** [comment]
Reproduced on a live site, WP Rocket **3.23.2.1** (latest), **WordPress 7.1**, **PHP 8.2.33**, theme **Woodmart**.

Every request fatals during bootstrap:

Uncaught TypeError: substr(): Argument #1 ($string) must be of type string, int given
in wp-rocket/inc/ThirdParty/Plugins/CDN/Cloudflare.php:562
#0 Cloudflare.php(562): substr()
#1 Cloudflare.php(535): WP_Rocket\ThirdParty\Plugins\CDN\Cloudflare->unregister_callback()
#2 class-wp-hook.php(353): ...->unregister_cloudflare_clean_on_post()

Root cause: in `unregister_callback()` the `$key` iterated from
`$wp_filter['clean_post_cache']->callbacks[$priority]` is an **int** (a numeric
callback key registered by the theme). The file declares `strict_types=1`, so
`substr( $key, ... )` throws a TypeError → site-wide fatal.

Note: the **Cloudflare add-on is disabled** (`do_cloudflare = 0`, empty
credentials), yet this code path still runs.

Fix is a simple cast:
```php
if ( substr( (string) $key, - strlen( $method ) ) !== $method ) {

Please ship it in a release.

**Comment by arthurvanl** [comment]
Had the same issue! The fix worked instantly. Thanks!

**Comment by DahmaniAdame** [comment]
@hellofromahmed let's take care of this one as well.

**Comment by hanna-meda** [comment]
Initial TP: https://wpmediaqa.testrail.io/index.php?/runs/view/1340
