### ISSUE TITLE
Godaddy compatibility - null passed to argument #1 $search of str_replace - array|string expected

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#7135]
**Describe the bug**
User reports the following error:

`Fatal error: Uncaught TypeError: str_replace(): Argument #1 ($search) must be of type array|string, null given in /var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Hostings/Godaddy.php:152 Stack trace: #0 /var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Hostings/Godaddy.php(152): str_replace(NULL, '160.153.168.4', '/var/www/wp-con...') #1 /var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Hostings/Godaddy.php(107): WP_Rocket\ThirdParty\Hostings\Godaddy->purge_request('BAN', '/var/www/wp-con...') #2 /var/www/wp-includes/class-wp-hook.php(324): WP_Rocket\ThirdParty\Hostings\Godaddy->clean_file('/var/www/wp-con...') #3 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #4 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /var/www/wp-content/plugins/wp-rocket/inc/functions/files.php(585): do_action('before_rocket_c...', '/var/www/wp-con...') #6 /var/www/wp-content/plugins/wp-rocket/inc/common/purge.php(249): rocket_clean_files(Array) #7 /var/www/wp-includes/class-wp-hook.php(326): rocket_clean_post(23593) #8 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #9 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #10 /var/www/wp-includes/post.php(7436): do_action('clean_post_cach...', 23593, Object(WP_Post)) #11 /var/www/wp-includes/post.php(4761): clean_post_cache(Object(WP_Post)) #12 /var/www/wp-includes/post.php(4995): wp_insert_post(Array, false, true) #13 /var/www/wp-admin/includes/post.php(453): wp_update_post(Array) #14 /var/www/wp-admin/post.php(227): edit_post() #15 {main} thrown in /var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Hostings/Godaddy.php on line 152`

**To Reproduce**
Not entirely sure what causes it, but any case out of WP Rocket's control where `wp_parse_url()` returns anything other than a `string` or `array` would cause this error.

**Expected behavior**
We should protect against cases we can't control where `wp_parse_url()` returns value of type other than `string` or `array` by doing a type check here:
https://github.com/wp-media/wp-rocket/blob/4542d7b8fd82e28c985a98ca7eb34b12890b50ea/inc/ThirdParty/Hostings/Godaddy.php#L152

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2771218400/525430

**Comment by johan-las** [comment]
I got a similar Fatal error.

The Fatal error is triggered when WP Rocket is active with **_Molongui Authorship_** plugin.
I can replicate it on page edition with _Elementor_. The consequence is that we can't save the page.

On the reported case, the hosting is **_Godaddy_** and the Fatal error come from `purge_request()` function in `ThirdParty/Hostings/Godaddy.php` at this [line](https://github.com/wp-media/wp-rocket/blob/ad2d1a00b05c4b8954d6ae20267b8d1c925ba4cf/inc/ThirdParty/Hostings/Godaddy.php#L152)

This happens because the **_Molongui Authorship_** plugin override the `get_author_posts_url()` function so the URL look like `#molongui-disabled-link`


As a **temporary solution**, the following Snippet code, solve the issue:

```
function filter_invalid_purge_urls( $purge_urls, $post ) {  
    return array_filter( $purge_urls, function( $url ) {  
        // Remove URLs that are fragments or invalid  
        return ! empty( $url ) && is_string( $url ) && strpos( $url, '#' ) !== 0;  
    });  
}  
add_filter( 'rocket_post_purge_urls', 'filter_invalid_purge_urls', 10, 2 );
```


**Fatal error Stack trace:**

```
PHP Fatal error: Uncaught TypeError: str_replace(): Argument #1 ($search) must be of type array|string, null given in /var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Hostings/Godaddy.php:152

Stack trace:

#0 /var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Hostings/Godaddy.php(152): str_replace(NULL, 'XXX.XXX.XXX.XXX', '#molongui-disab...')
#1 /var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Hostings/Godaddy.php(107): WP_Rocket\ThirdParty\Hostings\Godaddy->purge_request('BAN', '#molongui-disab...')
#2 /var/www/wp-includes/class-wp-hook.php(324): WP_Rocket\ThirdParty\Hostings\Godaddy->clean_file('#molongui-disab...')
#3 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /var/www/wp-content/plugins/wp-rocket/inc/functions/files.php(585): do_action('before_rocket_c...', '#molongui-disab...')
#6 /var/www/wp-content/plugins/wp-rocket/inc/common/purge.php(242): rocket_clean_files(Array)
#7 /var/www/wp-includes/class-wp-hook.php(326): rocket_clean_post(2792)
#8 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#9 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 /var/www/wp-includes/post.php(7662): do_action('clean_post_cach...', 2792, Object(WP_Post))
#11 /var/www/wp-includes/post.php(4980): clean_post_cache(Object(WP_Post))
#12 /var/www/wp-includes/post.php(5214): wp_insert_post(Array, false, true)
#13 /var/www/wp-content/plugins/elementor/core/settings/page/manager.php(360): wp_update_post(Array)
#14 /var/www/wp-content/plugins/elementor/core/settings/page/manager.php(122): Elementor\Core\Settings\Page\Manager->save_post_status(2792, 'publish')
#15 /var/www/wp-content/plugins/elementor/core/base/document.php(1798): Elementor\Core\Settings\Page\Manager->ajax_before_save_settings(Array, 2792)
#16 /var/www/wp-content/plugins/elementor/core/base/document.php(856): Elementor\Core\Base\Document->save_settings(Array)
#17 /var/www/wp-content/plugins/elementor/core/documents-manager.php(548): Elementor\Core\Base\Document->save(Array)
#18 [internal function]: Elementor\Core\Documents_Manager->ajax_save(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#19 /var/www/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#20 /var/www/wp-includes/class-wp-hook.php(324): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#21 /var/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#22 /var/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#23 /var/www/wp-admin/admin-ajax.php(192): do_action('wp_ajax_element...')
#24 {main}

thrown in /var/www/wp-content/plugins/wp-rocket/inc/ThirdParty/Hostings/Godaddy.php on line 152
```

**To Reproduce**
Steps to reproduce the behavior:
1. On a WordPress with WP Rocket + Molongui Authorship plugin + Elementor editor
2. Edit a page and click the _Publish_ button
3. A 500 error message is shown on the bottom left of the page.

![Image](https://github.com/user-attachments/assets/e8c1ba23-ed23-46a2-ae8e-69d7384fa694)



**Additional context**
Ticket: https://secure.helpscout.net/conversation/2984017853/570460?viewId=8127840
Slack: https://group-onecom.slack.com/archives/C08F4M3BBJL/p1751285226170819

**Comment by WordPresseur** [comment]
Another case: https://secure.helpscout.net/conversation/3059299720/583985
